# 이 파일은 그라파나 데이터 소스를 자동으로 설정합니다.
apiVersion: 1

datasources:
  - name: Prometheus # 그라파나에 표시될 데이터 소스 이름
    type: prometheus
    access: proxy # 그라파나 백엔드를 통해 프로메테우스에 접근
    orgId: 1
    uid: 'my-prometheus-ds-unique-id' # 데이터 소스의 고유 ID
    url: http://prometheus:9090 # Docker 네트워크 내부 주소
    isDefault: true # 이 데이터 소스를 기본값으로 설정
    editable: true

