name: 'Step 1: Setup IAM for GitHub Actions'

on:
  # 이 워크플로우는 수동으로만 실행되도록 설정합니다.
  workflow_dispatch:

jobs:
  provision-iam:
    name: Provision IAM Role for GitHub Actions
    runs-on: ubuntu-latest
    
    # 이 작업은 아직 IAM 역할을 사용할 수 없으므로, 액세스 키를 직접 사용합니다.
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        # iam.tf 파일이 있는 terraform 폴더를 지정합니다.
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: |
          # terraform 폴더에서 apply를 실행합니다.
          terraform -chdir=terraform apply -auto-approve
          echo "✅ IAM Role and OIDC Provider setup complete."
          echo "Please copy the 'github_actions_role_arn' output and save it as a new GitHub Secret named 'AWS_IAM_ROLE_ARN'."
