apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
  labels:
    app: my-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
        - name: my-website
          image: <ECR_IMAGE_URI>
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "<DB_HOST>"
            - name: DB_USER
              value: "<DB_USER>"
            - name: DB_PASSWORD
              value: "<DB_PASSWORD>"
            - name: DB_NAME
              value: "<DB_NAME>"
            - name: SESSION_SECRET
              value: "<SESSION_SECRET>"
            - name: OPENWEATHERMAP_API_KEY_SECRET
              value: "<OPENWEATHERMAP_API_KEY>"
            - name: MAPS_API_KEY_SECRET
              value: "<MAPS_API_KEY_SECRET>"
            - name: SNS_TOPIC_ARN
              value: "<SNS_TOPIC_ARN>"
