apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
  labels:
    app: my-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
        - name: my-website
          image: 501257812675.dkr.ecr.ap-northeast-2.amazonaws.com/my-node-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MYSQL_HOST
              value: "your-mysql-host.rds.amazonaws.com"
            - name: MYSQL_USER
              value: "your-db-user"
            - name: MYSQL_PASSWORD
              value: "your-db-password"
            - name: MYSQL_DATABASE
              value: "your-db-name"
            - name: API_KEY
              value: "your-weather-api-key"
---
apiVersion: v1
kind: Service
metadata:
  name: my-website-service
spec:
  selector:
    app: my-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
