name: Terraform Apply with Terraform Cloud

on:
  push:
    branches:
      - main  # 또는 사용할 브랜치 이름

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform Plan & Apply

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
